app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired, Email, Length
from flask_wtf.file import FileField, FileRequired

from app.custom_validators import WordLength

class UpdateProfileForm(FlaskForm):
    """Form for updating user profile"""
    firstname = StringField('Firstname', validators=[DataRequired()])
    lastname = StringField('Lastname', validators=[DataRequired()])
    email = email = StringField('Email', validators=[DataRequired(), Email()])
    phone = IntegerField('Phone Number', validators=[DataRequired()])
    about_me = TextAreaField('About Me', validators=[DataRequired()])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    subject = StringField("Subject", validators=[DataRequired(), Length(min=4), WordLength(min=1, max=10, message='Subject must have 1 to 10 words')])
    post_image = FileField('Article Image')
    body = StringField("Body", description='(500 to 3000 words)', validators=[DataRequired(), WordLength(min=500, max=3000, message='Body must have 500 to 3000 words.')])
    tag = SelectMultipleField('Select 3 or less Tags (*Hold down the Ctrl Key to select many)', coerce=int, validators=[DataRequired(), Length(max=3, message='Please select less than 4 tags')])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Comment')


class ProfilePhotoForm(FlaskForm):
    profile_photo = FileField(validators=[FileRequired()])
    submit = SubmitField('Save')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views
from app.models import Permission

@home.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/home/views.py
import cloudinary
import hashlib
import os
import cloudinary.uploader
from flask import render_template, flash, redirect, url_for, request, current_app, abort, make_response, Markup as markup, send_from_directory
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from app import db
from . import home
from app.models import User, Permission, Post, Comment, Tag, categories
from .forms import UpdateProfileForm, PostForm, CommentForm, ProfilePhotoForm
from app.decorators import permission_required
from app.emails import send_email

cloudinary = cloudinary

@home.route('/')
def home_page():
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_user_posts
    else:
        if not current_user.is_administrator():
            query = Post.query.filter_by(approved=True)
        else:
            query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(page, per_page = 6, error_out=False)
    posts = pagination.items
    return render_template('home/index.html', posts=posts, show_followed=show_followed, markup=markup, pagination=pagination, title='Home', active='home')


# ALL ROUTES RELATED TO TOPICS
@home.route('/topics')
def topics():
    topics = Tag.query.order_by(Tag.name).all()
    return render_template('home/topics.html', topics=topics, active='topics', title='Topics')


@home.route('/topics/<string:tag_name>')
def tag_posts(tag_name):
    """Route for viewing all posts under a topic/tag"""
    page = request.args.get('page', 1, type=int)
    tag = Tag.query.filter_by(name=tag_name.lower()).first()
    tagposts = tag.posts
    pagination = tagposts.order_by(Post.timestamp.desc()).paginate(page, per_page = 6, error_out=False)
    posts = pagination.items
    return render_template('home/tag_posts.html', posts=posts, markup=markup, tag_name=tag.name.lower(), pagination=pagination, title='Topic: {}'.format(tag.name), active='topics')

# END OF ALL ROUTES RELATED TO TOPICS

# ALL ROUTES RELATED TO POSTS

@home.route('/new_article', methods=['GET', 'POST'])
@login_required
def write_article():
    form = PostForm()
    form.tag.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
        if os.getenv('FLASK_ENV') == 'production':
            # result = cloudinary.uploader.upload(form.post_image.data, proxy = "http://proxy.server:3128")
            result = cloudinary.uploader.upload(form.post_image.data)
        else:
            result = cloudinary.uploader.upload(form.post_image.data)
        post = Post(subject=form.subject.data, image_url=result['secure_url'],body=form.body.data, author=current_user._get_current_object())
        post = Post(subject=form.subject.data, body=form.body.data, author=current_user._get_current_object())
        for id in form.tag.data:
                post.tags.append(Tag.query.get(id))
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.home_page'))
    return render_template('home/write_post.html', form=form, title='New Post')

@home.route('/post/<int:id>', methods=['GET', 'POST'])
def view_post(id):
    post = Post.query.get_or_404(id)
    if current_user is not post.author and not current_user.is_administrator() and post.is_approved() == False:
        abort(404)
    form = CommentForm()
    if current_user.is_authenticated and form.validate_on_submit():
        comment = Comment(body=form.body.data, post=post, author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('.view_post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1)/6+1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(page, per_page=6, error_out=False)
    comments = pagination.items
    return render_template('home/post.html', markup=markup, posts=[post], form=form, comments=comments, pagination=pagination, title='Post')


@home.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm(obj=post)
    form.tag.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if form.validate_on_submit():
        post.subject = form.subject.data
        if os.getenv('FLASK_ENV') == 'production':
            # result = cloudinary.uploader.upload(form.post_image.data, proxy = "http://proxy.server:3128")
            result = cloudinary.uploader.upload(form.post_image.data)
        else:
            result = cloudinary.uploader.upload(form.post_image.data)
        post.image_url = result['secure_url']
        post.body = form.body.data
        posttags = db.session.query(categories).filter_by(post_id=id).all()
        for id in form.tag.data:
            if (post.id, id) not in posttags:
                post.tags.append(Tag.query.get(id))
        db.session.commit()
        return redirect(url_for('.view_post', id=post.id))
    form.subject.data = post.subject
    # form.post_image.data = post.image_url
    form.body.data = post.body
    form.tag.default = [tag_id for tag_id in db.session.query(categories).filter_by(post_id=post.id).all()]
    form.process(obj=post)
    return render_template('home/write_post.html', markup=markup, form=form, post=post, title='Edit Post')


@home.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    Post.delete(post)
    return redirect(url_for('.home_page'))


@home.route('/all')
@login_required
def show_all_posts():
    resp = make_response(redirect(url_for('.home_page', active_pill='all')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)
    return resp

@home.route('/followed_user_posts')
@login_required
def show_followed_user_posts():
    resp = make_response(redirect(url_for('.home_page')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp

# END OF ALL ROUTES RELATED TO POSTS

# ALL ROUTES RELATED TO USER PROFILE

@home.route('/profile/<int:id>')
@login_required
def profile(id):
    # user = current_user
    user = User.query.get_or_404(id)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('home/profile.html',markup=markup, user=user, id=user.id, posts=posts, title='Profile', active='profile')


@home.route('/profile/update', methods=['GET', 'POST'])
@login_required
def profile_update():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.email = form.email.data
        current_user.phone = form.phone.data
        current_user.about_me = form.about_me.data
        current_user.avatar_hash = hashlib.md5(form.email.data.encode('utf-8')).hexdigest()
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.profile', id=current_user.id))
    form.firstname.data = current_user.firstname
    form.lastname.data = current_user.lastname
    form.phone.data = current_user.phone
    form.email.data = current_user.email
    form.about_me.data = current_user.about_me
    
    return render_template('home/update_profile.html', form=form, title='Update Profile')

@home.route('/profile_photo/upload', methods=['GET', 'POST'])
def upload_profile_photo():
    form = ProfilePhotoForm()
    if form.validate_on_submit():
        file = form.profile_photo.data
        if os.getenv('FLASK_ENV') == 'production':
            # result = cloudinary.uploader.upload(file, proxy = "http://proxy.server:3128")
            result = cloudinary.uploader.upload(file)
        else:
            result = cloudinary.uploader.upload(file)
        current_user.profile_photo_path = result['secure_url']
        # filename = secure_filename(file.filename)
        # f = os.path.join(os.path.abspath('app/static/profile_photos'), filename)
        # file.save(f)
        # current_user.profile_photo_path = f
        db.session.commit()
        return redirect(url_for('.profile', id=current_user.id))

    return render_template('home/profile_photo_form.html', form=form, title='Profile photo')

home.route('/profile_pic/<path:filename>')
def profile_pic(filename):
        return send_from_directory('profile_photos', "filename", as_attachment=True)

# END OF ALL ROUTES RELATED TO USER PROFILE

# ALL ROUTES RELATED TO FOLLOWING

@home.route('/follow/<int:id>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(id):
    user = User.query.get_or_404(id)
    if user is None:
        flash('Invalid User')
        return redirect(url_for('.home_page'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('.profile', id=id))
    current_user.follow(user)
    # flash('You are now following %s.' % user.firstname)
    return redirect(url_for('.profile', id=id))

@home.route('/followers/<int:id>')
@login_required
def followers(id):
    # This route shows all followers of a user
    user = User.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(page, per_page=10, error_out=False)
    followed_by = [{'user': item.follower, 'timestamp': item.timestamp} for item in pagination.items]

app/templates/home/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-content">
            <div class="profile-thumbnail">
                <a href="{{ url_for('.profile', id=comment.author.id, firstname=comment.author.firstname) }}">
                    <img class="rounded-circle profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
                </a>
            </div>
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author">
                <a href="{{ url_for('.profile',id=comment.author.id) }}">
                    {{ comment.author.firstname }}
                </a>
            </div>
            <div class="comment-body">
                {% if comment.disabled %}
                <p></p><i>This comment has been disabled by a moderator.</i></p>
                {% endif %}
                {% if moderate or not comment.disabled %}
                {{ comment.body }}
                {% endif %}</div>
            {% if moderate %}
            <br>
            {% if comment.disabled %}
            <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable',
id=comment.id, page=page) }}">Enable</a>
            {% else %}
            <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable',
id=comment.id, page=page) }}">Disable</a>
            {% endif %}
            {% endif %}
            <div class="float-right comment-footer">
                {% if current_user == comment.author %}
                <a href="{{ url_for('.edit_comment', id=comment.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                <a href="{{ url_for('.delete_comment', id=comment.id) }}">
                    <span class="label label-primary">Delete</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('.edit_comment', id=comment.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                <a href="{{ url_for('.delete_comment', id=comment.id) }}">
                    <span class="label label-primary">Delete</span>
                </a>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/home/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post-col">
        <img class="img-fluid post-image" src="{{ post.image_url }}">
        <br><br>
        <div class="post-content">
            <div class="text-center">
                <a href="{{ url_for('.profile', id=post.author.id) }}">
                        {% if post.author.profile_photo_path %}
                        <img class="img-fluid rounded-circle profile-pic-small" src="{{ post.author.user_image() }}" alt="">
                        {% else %}
                        <img class="rounded-circle" src="{{ post.author.gravatar(size=40) }}">
                        {% endif %}
                </a>&nbsp&nbsp
                <em>Article by </em><a href="{{ url_for('.profile',id=post.author.id) }}">
                    {{ post.author.firstname }}
                </a>&nbsp&nbsp, {{ moment(post.timestamp).fromNow() }}
            </div><br>
            <div class="text-center">
                <h4 class="text-center font-weight-bold">{{ post.subject }}</h4>
                <!-- <div class="post-body">{{ markup(post.body) }}</div> -->
                <br><a href="{{ url_for('home.view_post', id=post.id) }}" class="btn btn-primary readmore-btn">Read
                    Article</a>
            </div>
            <div class="post-tags mt-2 text-center">
                {% for tag in post.tags %}
                <span data-toggle="tooltip" data-placement="bottom" data-html="true" title="<strong>{{ tag.posts.count() }} Articles tagged</strong><br>{{ tag.description }}"><a
                        href="{{ url_for('.tag_posts', tag_name=tag.name.lower()) }}">{{ tag.name }}</a></span>
                {% endfor %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/home/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container-fluid bg">
    <div class=" mx-auto text-center bg-content">
        <!-- <hr> -->
        <h1 class="mx-auto font-weight-bold">Discipleship, Evangelism, Missions and Leadership
            Development</h1><br>
        {% if current_user.can(Permission.WRITE_ARTICLES) %}
        <a class="btn btn-primary" href="{{ url_for('home.write_article') }}">
            <h4><i class="fa fa-pencil-square-o"></i> Write article</h4>
        </a>
        {% endif %}
        <!-- <hr> -->
    </div>
</div>
<div class="container-fluid mt-5">
        <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {% if not show_followed %}active{% endif %}" href="{{ url_for('.show_all_posts') }}">All</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if show_followed %}active{% endif %}" href="{{ url_for('.show_followed_user_posts') }}">Followed</a>
                </li>
            </ul>
    <div class="container">
        {% include 'home/_posts.html' %}
    </div>
    <div class="container mx-auto pagination">
        {{ macros.pagination_widget(pagination, '.home_page') }}
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/home/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}Flasky - Comment Moderation{% endblock %}
{% block body %}
{% block content %}
<div class="page-header">
<h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% include 'home/_comments.html' %}
{% if pagination %}
<div class="pagination">
{{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}
{% endblock %}

app/templates/home/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
{% for post in posts %}
<div class="jumbotron">
    <img class="img-fluid rounded mx-auto d-block post-image" src="{{ post.image_url }}">
    <br><br><div class="post-content">
        <div class="text-center">
            <a href="{{ url_for('.profile', id=post.author.id) }}">
                    {% if post.author.profile_photo_path %}
                    <img class="rounded-circle profile-thumbnail" src="{{ post.author.profile_photo_path }}" alt="" height="40" width="40"
                    {% else %}
                    <img class="rounded-circle profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
                    {% endif %}
            </a>&nbsp&nbsp
            <a href="{{ url_for('.profile',id=post.author.id) }}">
                <em> by </em>{{ post.author.firstname }}
            </a>&nbsp&nbsp, {{ moment(post.timestamp).fromNow() }}
        </div><br>
        <div class="">
            <h2 class="text-center font-weight-bold">{{ post.subject }}</h2>
            <p class="">{{ markup(post.body) }}</p>
        </div>
        <div class="post-tags mt-2 text-center">
            <span>
                {% for tag in post.tags %}
                <span data-toggle="tooltip" data-placement="bottom" data-html="true" title="<strong>{{ tag.posts.count() }} Articles with this tag</strong><br>{{ tag.description }}"><a href="{{ url_for('.tag_posts', tag_name=tag.name.lower()) }}">{{ tag.name }}</a></span>,
                {% endfor %}
            </span>
        </div>
        <div class="float-right">
            {% if current_user == post.author or current_user.is_administrator() %}
            <a class="btn btn-success" href="{{ url_for('.edit_post', id=post.id) }}">Edit</a>
            <a class="btn btn-danger" href="{{ url_for('.delete_post', id=post.id) }}">Delete</a>
            {% endif %}
            {% if current_user.is_administrator() and not post.is_approved() %}
            <a class="btn btn-primary" href="{{ url_for('admin.approve_article', id=post.id) }}">Approve</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="comment-form jumbotron mx-auto">
        {% include '_form_errors.html' %}
        {{ wtf.quick_form(form) }}
    </div>
    {% include 'home/_comments.html' %}
</div>
{% endblock %}
{% endblock %}

app/templates/home/profile.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4 p-5">
            {% if user.profile_photo_path %}
            <img class="img-fluid rounded img-thumbnail profile-pic" src="{{ user.profile_photo_path }}" alt="">
            {% else %}
            <img class="rounded img-thumbnail profile-pic" src="{{ user.gravatar(size=256) }}">
            {% endif %}
            <a class="change-image" href="{{ url_for('.upload_profile_photo') }}">Change picture</a>
        </div>
        <div class="col-md-4  p-5">
            <h1>{{ user.firstname +' '+ user.lastname }}</h1>
            {% if current_user.is_administrator() %}
            <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
            {% endif %}
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            <p>
                Member since <em>{{ moment(user.member_since).format('L') }}</em>.
                Last seen <i>{{ moment(user.last_seen).fromNow() }}</i>.
            </p>
            {% if current_user == user %}
            <a class="btn btn-success" href="{{ url_for('home.profile_update') }}">Edit Profile</a>
            <a class="btn btn-danger" href="{{ url_for('auth.delete_account_initial_step') }}">Delete Account</a>
            {% endif %}<br><br>
            {% if current_user.is_administrator() %}
            <span><a href="{{ url_for('admin.edit_userprofile', id=user.id) }}">Edit User Profile</a></span>
            {% endif %}
            {% if current_user.can(Permission.FOLLOW) and user != current_user %}
            {% if not current_user.is_following(user) %}
            <a href="{{ url_for('.follow', id=user.id) }}" class="btn btn-primary">Follow</a>
            {% else %}
            <a href="{{ url_for('.unfollow', id=user.id) }}" class="btn btn-primary">Unfollow</a>
            {% endif %}
            {% endif %}
            <a href="{{ url_for('.followers', id=user.id) }}">
                Followers: <span class="badge">{{ user.followers.count() }}</span>
            </a>
            <a href="{{ url_for('.following', id=user.id) }}">
                Following: <span class="badge">{{ user.followed.count() }}</span>
            </a>
            {% if current_user.is_authenticated and user != current_user and
            user.is_following(current_user) %}
            | <span class="label label-default">Follows you</span>
            {% endif %}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
<div class="container">
    {% include 'home/_posts.html' %}
</div>
{% endblock %}
{% endblock %}

app/templates/home/profile_photo_form.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        {% include '_form_errors.html' %}
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/home/tag_posts.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container-fluid mt-5">
    <br>
    <h3 class="text-center font-weight-bold mt-5">Articles Tagged: {{ tag_name.capitalize() }}</h3><br>
    {% include 'home/_posts.html' %}
</div>
<div class="container mx-auto pagination">
    {{ macros.pagination_widget(pagination, '.tag_posts', tag_name=tag_name) }}
</div>
{% endblock %}
{% endblock %}

app/templates/home/topics.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="jumbotron">
            {% if current_user.is_administrator() %}
            <a class="btn btn-primary" href="{{ url_for('admin.add_tag') }}">Add Topics</a>
            {% endif %}
        <ul>
            {% for topic in topics %}
            <li><a href="{{ url_for('.tag_posts', tag_name=topic.name.lower()) }}">{{ topic.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/home/update_profile.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container">
    {% if form.errors %}
    <ul class="errors">
        {% for field_name, field_errors in form.errors|dictsort if field_errors %}
        {% for error in field_errors %}
        <li class="alert alert-warning">{{ form[field_name].label }}: {{ error }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
    {% endif %}
    <div class="jumbotron">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-row">
                <div class="col">
                    {{ form.firstname.label }}
                    {{ form.firstname(class="form-control", placeholder="First name") }}
                </div>
                <div class="col">
                    {{ form.lastname.label }}
                    {{ form.lastname(class="form-control", placeholder="Last name") }}
                </div>
            </div>
            <div class="form-group">
                {{ form.email.label }}
                {{ form.email (class="form-control", placeholder="Enter email", **{'aria-describedby': "emailHelp"})}}
            </div>
            <div class="form-group">
                {{ form.phone.label }}
                {{ form.phone (class="form-control", placeholder="Phone Number")}}
            </div>
            <div class="form-group">
                {{ form.about_me.label }}
                {{ form.about_me(class="form-control", placeholder="Something about yourself")}}
            </div>
            {{ form.submit (class="btn btn-primary")}}
        </form>
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/home/write_post.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block body %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        {% include '_form_errors.html' %}
        <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.subject.label }}
                {{ form.subject(class="form-control") }}
            </div>
            <div class="form-group">
              {{ form.post_image.label }}
              {{ form.post_image(class="form-control") }}
          </div>
            <div class="form-group">
                {{ form.body.label }}
                {{ form.body(type='hidden') }}
                <div class="" id="editor-container"></div>
            </div>
            <div class="form-group">
                {{ form.tag.label }}
                {{ form.tag(class="form-control") }}
            </div>
            <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#post-preview">
    Preview
  </button>
            {{ form.submit(class="btn btn-primary") }}
        </form>
    </div>
</div>
  
  <!-- Modal -->
  <div class="modal fade" id="post-preview" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Article Preview</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% endblock %}